[log]
  ## Logging configuration
  ## 'stdout' enables logging to standard output
  stdout = true
  
  ## 'filename' is the path to the log file
  ## if empty, logging to file is disabled
  filename = "./metrical.log"
  
  ## 'level' sets the logging level
  ## valid levels are: DEBUG, INFO, WARN, ERROR
  level = "INFO"

[http]
  ## HTTP server configuration
  ## 'listen' is the address to bind to (e.g. ":3000" for all interfaces on port 3000)
  ## if listen is empty, no HTTP server will be started
  listen = ":3000"
  ## 'adv_addr' is the address to advertise to clients (e.g. "http://myhost:3000")
  adv_addr = "http://localhost:3000"
  ## 'dashboard' is the path to the dashboard (e.g. "/dashboard")
  ## if 'dashboard' is empty, no dashboard will be served
  [[http.dashboard]]
    path = "/dashboard"
  ##
  ## tails
  ##
  #[[http.tail]]
  #  path = "/term/logs"
  #  [[http.tail.file]]
  #    filename = "${log-filename}"
  #    label = "metrical"
  #    highlights = ["level", "slog-text"]
  #  [[http.tail.file]]
  #    filename = "/var/log/syslog"
  #    label = "syslog"
  #    highlights = ["syslog", "level"]
  #  [[http.tail.file]]
  #    filename = "/var/log/auth.log"
  #    label = "auth.log"
  #    highlights = ["level"]
  ##
  ## terminals
  ##
  #[[http.term]]
  #  path = "/term/home"
  #  command = "/usr/bin/zsh"
  #  args = ["-il"]
  #  dir = "/home/user_id"
  #[[http.term]]
  #  path = "/term/htop"
  #  command = "/usr/bin/htop"
  #  args = []
  #  dir = "/home/user_id"
  ##
  ## SSH terminals
  ##
  #[[http.ssh]]
  #  path = "/term/ssh-host"
  #  host ="your.ssh.host"
  #  port = 22
  #  user = "your_id"
  #  password = "your_password_here"
  #  keyfile = "/home/your_id/.ssh/id_rsa"
  ##
  ## If 'ssh.command' is empty, it will start a shell session
  ## otherwise, it will run the specified command upon connection
  #  command = "tail -F /var/log/syslog"
  ##
  ## If 'ssh.via' is specified, it will use the jump hosts to connect
  ## to the target host.
  #[[http.ssh.via]]
  #  host = "jump.host1"
  #  port = 22
  #  user = "jump_id1"
  #  password = "jump_password1"
  #  keyfile = "/home/your_id/.ssh/id_rsa"

[data]
  sampling_interval = "10s"
  input_buffer = 1000

  ## optional prefix for all timeseries names
  ## it will be prepended to the name of metrics for publish to expvar
  ## refer to https://pkg.go.dev/expvar for details
  prefix = ""

  ## persistence store configuration
  ## if empty, no persistence will be used (in-memory only)
  # store = "sqlite:/path/to/metrical.db"
  store = ""

  [data.filter]
    includes = []
    excludes = []

  ## Define the timeseries to be collected and stored
  ## 'id' is a unique identifier for the timeseries, It must start with a letter and
  ##      can contain only uppercase letters, numbers, and underscores.
  ## 'title' is a human-readable name for the timeseries.
  ## 'interval' is the sampling interval for the timeseries (e.g. "10s" for 10 seconds)
  ## 'length' is the number of data points to retain in the timeseries.
  [[data.timeseries]]
    id = "TS_10S"
    title = "15 Minutes of 10 sec"
    interval = "10s"
    length = 90 # 15 minutes

  [[data.timeseries]]
    id = "TS_1M"
    title = "4 Hours of 1 min"
    interval = "60s"
    length = 240 # 4 hours

  [[data.timeseries]]
    id = "TS_1H"
    title = "10 Days of 1 hour"
    interval = "60m"
    length = 240 # 10 days

  [[data.timeseries]]
    id = "TS_1D"
    title = "480 Days of 1 day"
    interval = "24h"
    length = 240 # 480 days
